services:
  db:
    image: postgres:16
    container_name: mp_db
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${PGPORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/00_init:/docker-entrypoint-initdb.d:ro

  # Optional pgAdmin (web UI)
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: mp_pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=adminpass
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db

volumes:
  pgdata:
